SchoolQuiz/urls.py
from django.conf.urls import url, include
from django.contrib import admin

from SchoolQuiz import settings

urlpatterns = [
  url(r'^admin/', admin.site.urls),
  url(r'^auth/', include('auth0.urls', namespace='auth0')),
  url(r'^', include('quiz.urls', namespace='quiz')),
]

quiz/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
  url(r'^$', views.HomeView.as_view(), name='home'),
  url(r'^register-school/$', views.RegisterSchool.as_view(), name='register-school'),
  url(r'^quiz/new/$', views.NewQuiz.as_view(), name='new-quiz'),

  url(r'^quiz/(?P<quiz_id>[0-9]+)/(?P<question_num>[0-9]+)/$', views.QuizQuestionView.as_view(), name='quiz-question'),
  url(r'^quiz/result/(?P<student_id>[0-9]+)/(?P<quiz_id>[0-9]+)/$', views.QuizResultView.as_view(), name='quiz-result'),

  url(r'^register-teacher/$', views.RegisterTeacher.as_view(), name='register-teacher'),
  url(r'^teacher/$', views.TeacherHomeView.as_view(), name='teacher-home'),
  url(r'^^teacher/student/(?P<pk>[0-9]+)/$', views.TeacherStudentView.as_view(), name='teacher-student'),
  url(r'teacher/quiz/(?P<quiz_id>[0-9]+)/$', views.TeacherQuizView.as_view(), name='teacher-quiz'),
  url(r'^teacher/submit-score/$', views.SubmitScoreView.as_view(), name='submit-score'),

  url(r'^adm/home', views.AdminHomeView.as_view(), name='admin-home'),
]

quiz/models.py
from __future__ import unicode_literals

from django.contrib.auth.models import User
from django.core.exceptions import ObjectDoesNotExist
from django.db import models
from django.contrib.contenttypes.models import ContentType
from django.contrib.contenttypes.fields import GenericForeignKey, GenericRelation

# Create your models here.
from django.db.models import Sum
from django.utils import timezone


class Quiz(models.Model):
  name = models.CharField(max_length=100)
  quiz_commence_date = models.DateTimeField()
  standard = models.IntegerField()

  created_by = models.ForeignKey(User)

  created_at = models.DateTimeField(default=timezone.now)
  updated_at = models.DateTimeField(default=timezone.now)

  def get_num_of_questions(self):
    return MCQuestion.objects.filter(quiz=self).count()\
           + SubjectiveQuestion.objects.filter(quiz=self).count()

  def get_total_score(self):
    return MCQuestion.objects.filter(quiz=self).aggregate(score=Sum('score'))['score']\
           + SubjectiveQuestion.objects.filter(quiz=self).aggregate(score=Sum('score'))['score']

  def add_mc_question(self, question, choices, answer, question_num, score=1):
    inserted_choices = []
    inserted_answer = None

    for choice in choices:
      inserted_choice = Choice.objects.create(text=choice.strip())
      inserted_choices.append(inserted_choice)
      if choice == answer:
        inserted_answer = inserted_choice

    inserted_question = MCQuestion.objects.create(
      text=question.strip(),
      quiz=self,
      question_num=question_num,
      answer=inserted_answer,
      score=score
    )

    for choice in inserted_choices:
      inserted_question.choices.add(choice)

    return inserted_question

  def add_subjective_question(self, question, question_num, score=1):
    return SubjectiveQuestion.objects.create(
      quiz=self,
      question_num=question_num,
      text=question.strip(),
      score=score
    )

  def get_question_by_num(self, num):
    try:
      return {
        'type': 'mcq',
        'object': MCQuestion.objects.get(quiz=self, question_num=num),
      }
    except ObjectDoesNotExist:
      pass

    try:
      return {
        'type': 'sub',
        'object': SubjectiveQuestion.objects.get(quiz=self, question_num=num),
      }
    except ObjectDoesNotExist:
      pass

    return {
      'type': 'out_of_range',
      'object': None,
    }


class Choice(models.Model):
  text = models.TextField(max_length=500)

  created_at = models.DateTimeField(default=timezone.now)
  updated_at = models.DateTimeField(default=timezone.now)


class MCQuestion(models.Model):
  quiz = models.ForeignKey(Quiz)
  question_num = models.IntegerField()

  text = models.TextField(max_length=1000)
  choices = models.ManyToManyField(Choice, related_name='question')
  answer = models.ForeignKey(Choice)

  score = models.IntegerField(default=1)

  created_at = models.DateTimeField(default=timezone.now)
  updated_at = models.DateTimeField(default=timezone.now)


class SubjectiveQuestion(models.Model):
  quiz = models.ForeignKey(Quiz)
  question_num = models.IntegerField()

  text = models.TextField(max_length=1000)
  score = models.IntegerField(default=1)

  created_at = models.DateTimeField(default=timezone.now)
  updated_at = models.DateTimeField(default=timezone.now)


class School(models.Model):
  name = models.CharField(max_length=100)

  address = models.TextField(max_length=400)
  contact = models.CharField(max_length=15)
  alt_contact = models.CharField(max_length=15, blank=True, null=True)
  email = models.EmailField()
  website = models.URLField(blank=True, null=True)

  created_at = models.DateTimeField(default=timezone.now)
  updated_at = models.DateTimeField(default=timezone.now)


class Teacher(models.Model):
  user = models.OneToOneField(User, related_name='teacher')

  first_name = models.CharField(max_length=20)
  last_name = models.CharField(max_length=20)
  middle_name = models.CharField(max_length=20, blank=True, null=True)

  school = models.ForeignKey(School)
  standard = models.IntegerField()

  created_at = models.DateTimeField(default=timezone.now)
  updated_at = models.DateTimeField(default=timezone.now)

  def get_students(self):
    return Student.objects.filter(school=self.school).filter(standard=self.standard)

  def set_score(self, student, question, score=0):
    if student.school == self.school:
      try:
        answer = AnswerSheet.objects.get(
          student=student,
          content_type__model='subjectivequestion',
          object_id=question.id
        )
        if score > question.score:
          score = question.score
        answer.score = score
        answer.save()
        return answer
      except ObjectDoesNotExist:
        return None
    return None

  def get_past_quizzes(self):
    return Quiz.objects.filter(standard=self.standard)


class Student(models.Model):
  user = models.OneToOneField(User, related_name='student')

  first_name = models.CharField(max_length=20)
  last_name = models.CharField(max_length=20)
  middle_name = models.CharField(max_length=20, blank=True, null=True)

  school = models.ForeignKey(School)
  standard = models.IntegerField()
  roll_num = models.CharField(max_length=10, blank=True, null=True)

  created_at = models.DateTimeField(default=timezone.now)
  updated_at = models.DateTimeField(default=timezone.now)

  def get_upcoming_quizzes(self):
    return Quiz.objects.filter(standard=self.standard)\
      .filter(quiz_commence_date__gt=timezone.now())

  def get_attempted_quizzes(self):
    return Quiz.objects.filter(id__in=AnswerSheet.objects.filter(student=self)
                               .values_list('quiz__id', flat=True))

  def get_active_quizzes(self):
    return Quiz.objects.filter(standard=self.standard)\
      .filter(quiz_commence_date__day=timezone.now().day)\
      .filter(quiz_commence_date__month=timezone.now().month)\
      .filter(quiz_commence_date__year=timezone.now().year)

  def get_score_for_quiz(self, quiz):
    return self.get_answer_sheet_for_quiz(quiz).aggregate(score=Sum('score'))['score']

  def get_answer_sheet_for_quiz(self, quiz):
    return AnswerSheet.objects.filter(quiz=quiz).filter(student=self)

  def get_unattempted_mcquestions_for_quiz(self, quiz):
    attempted_mc_questions = AnswerSheet.objects\
      .filter(questions__quiz=quiz)\
      .filter(student=self)\
      .filter(content_type__model='MCQuestion').values_list('id', flat=True)

    return MCQuestion.objects.filter(quiz=quiz).exclude(id__in=attempted_mc_questions)

  def submit_answer(self, question, answer):
    if isinstance(question, MCQuestion):
      if question.answer == answer:
        score = question.score
      else:
        score = 0

      try:
        a_sheet = AnswerSheet.objects.get(student=self, object_id=question.id, content_type__model='mcquestion')
        if a_sheet.editable:
          a_sheet.answer = answer.text
          a_sheet.score = score
      except ObjectDoesNotExist:
        a_sheet = AnswerSheet(
          student=self,
          quiz=question.quiz,
          question=question,
          answer=answer.text,
          score=score
        )
      a_sheet.save()
      return a_sheet
    else:
      try:
        a_sheet = AnswerSheet.objects.get(student=self, object_id=question.id, content_type__model='subjectivequestion')
        if a_sheet.editable:
          a_sheet.answer = answer
      except ObjectDoesNotExist:
        a_sheet = AnswerSheet(
          student=self,
          quiz=question.quiz,
          question=question,
          answer=answer,
          score=None
        )
      a_sheet.save()
      return a_sheet

  def set_quiz_uneditable(self, quiz):
    AnswerSheet.objects.filter(student=self).filter(quiz=quiz).update(editable=False)


class AnswerSheet(models.Model):
  student = models.ForeignKey(Student)
  quiz = models.ForeignKey(Quiz)

  content_type = models.ForeignKey(ContentType, on_delete=models.CASCADE)
  object_id = models.PositiveIntegerField()
  question = GenericForeignKey('content_type', 'object_id')

  answer = models.CharField(max_length=1000)
  score = models.IntegerField(default=0, null=True)

  editable = models.BooleanField(default=True)

  created_at = models.DateTimeField(default=timezone.now)
  updated_at = models.DateTimeField(default=timezone.now)

  def is_correct(self):
    if self.content_type.model == 'MCQuestion':
      return self.answer == self.question.answer.text
    else:
      return None

  def is_unscored(self):
    if self.content_type.model == 'SubjectiveQuestion':
      return self.score is None
    else:
      return None

quiz/forms.py
from django import forms

from quiz.models import School, Quiz


class RegisterSchoolForm(forms.ModelForm):

  class Meta:
    model = School
    exclude = ('created_at', 'updated_at')

  def test_func(self):
    return self.requ


class NewQuizForm(forms.ModelForm):
  questions = forms.FileField(required=False, label='Upload Questions(*.csv)')

  class Meta:
    model = Quiz
    exclude = ('created_at', 'updated_at', 'created_by')

quiz/views.py
from django.shortcuts import get_object_or_404, redirect
from django.http import HttpResponse
from django.http import Http404
from django.core.urlresolvers import reverse_lazy

# Create your views here.
from django.views import View
from django.views.generic import CreateView
from django.views.generic import ListView
from django.views.generic import TemplateView, FormView, DetailView
from .mixins import AdminMixin, StudentMixin, TeacherMixin

from auth0.forms import TeacherRegisterForm
from quiz.forms import RegisterSchoolForm, NewQuizForm
from quiz.models import Quiz, Choice, AnswerSheet, School, Student


class HomeView(TemplateView):
  template_name = 'quiz/home.html'

  def get(self, request, *args, **kwargs):
    if hasattr(request.user, 'teacher'):
      return redirect('quiz:teacher-home')
    elif request.user.is_superuser:
      return redirect('quiz:admin-home')
    return super(HomeView, self).get(request, *args, **kwargs)


class AdminHomeView(AdminMixin, TemplateView):
  template_name = 'quiz/admin-home.html'


class TeacherHomeView(TeacherMixin, TemplateView):
  template_name = 'quiz/teacher-home.html'


class TeacherStudentView(TeacherMixin, DetailView):
  template_name = 'quiz/teacher-student.html'
  model = Student
  context_object_name = 'student'


class TeacherQuizView(TeacherMixin, TemplateView):
  template_name = 'quiz/teacher-quiz.html'

  def get_context_data(self, **kwargs):
    context = super(TeacherQuizView,self).get_context_data(**kwargs)
    quiz = get_object_or_404(Quiz, pk=kwargs['quiz_id'])
    context['quiz'] = quiz
    context['students'] = Student.objects.filter(id__in=AnswerSheet.objects.filter(quiz=quiz).values_list('student__id', flat=True))
    return context


class SubmitScoreView(TeacherMixin, View):

  def post(self, request, *args, **kwargs):
    answer = get_object_or_404(AnswerSheet, pk=request.POST.get('answer_id'))
    answer.score = request.POST.get('score')
    answer.save()
    return HttpResponse(content='', status=201)


class QuizQuestionView(StudentMixin, TemplateView):
  template_name = 'quiz/quiz-question.html'

  def get_context_data(self, **kwargs):
    quiz_id = kwargs['quiz_id']
    q_num = kwargs['question_num']

    question = get_object_or_404(Quiz, pk=quiz_id).get_question_by_num(q_num)

    if question['type'] == 'out_of_range':
      raise Http404

    context = {
      'question': question['object'],
      'is_mcq': question['type'] == 'mcq',
    }

    return context

  def post(self, request, *args, **kwargs):
    quiz_id = kwargs['quiz_id']
    q_num = int(kwargs['question_num'])

    quiz = get_object_or_404(Quiz, pk=quiz_id)
    question = get_object_or_404(Quiz, pk=quiz_id).get_question_by_num(q_num)

    if question['type'] == 'out_of_range':
      raise Http404
    elif question['type'] == 'mcq':
      answer = get_object_or_404(Choice, pk=request.POST.get('answer', -1))
    else:
      answer = request.POST.get('answer', 'answer_submission_error')

    request.user.student.submit_answer(question=question["object"], answer=answer)

    if q_num < quiz.get_num_of_questions():
      return redirect('quiz:quiz-question', quiz_id=kwargs['quiz_id'], question_num=(q_num + 1))

    request.user.student.set_quiz_uneditable(quiz)
    return redirect('quiz:quiz-result', quiz_id=kwargs['quiz_id'], student_id=request.user.student.id)


class QuizResultView(TemplateView):
  template_name = 'quiz/quiz_result.html'
  context_object_name = 'answer_sheet'

  def get(self, request, *args, **kwargs):
    return super(QuizResultView, self).get(request, *args, **kwargs)

  def get_context_data(self, **kwargs):
    quiz = get_object_or_404(Quiz, pk=self.kwargs['quiz_id'])
    student = get_object_or_404(Student, pk=self.kwargs['student_id'])
    context = {
      'answer_sheet': student.get_answer_sheet_for_quiz(quiz=quiz),
      'quiz': quiz,
      'score': student.get_score_for_quiz(quiz=quiz)
    }
    return context


class RegisterSchool(AdminMixin, CreateView):
  template_name = 'quiz/register-school.html'
  form_class = RegisterSchoolForm
  success_url = reverse_lazy('quiz:register-school')


class RegisterTeacher(AdminMixin, FormView):
  template_name = 'auth0/register-teacher.html'
  form_class = TeacherRegisterForm
  success_url = reverse_lazy('quiz:teacher-home')

  def get_context_data(self, **kwargs):
    context = super(RegisterTeacher, self).get_context_data()
    context['schools'] = School.objects.all().order_by('name')
    return context

  def form_valid(self, form):
    form.save()
    return super(RegisterTeacher, self).form_valid(form)


class NewQuiz(AdminMixin, FormView):
  template_name = 'quiz/new-quiz.html'
  form_class = NewQuizForm
  success_url = reverse_lazy('quiz:new-quiz')

  def post(self, request, *args, **kwargs):
    form_class = self.get_form_class()
    form = self.get_form(form_class)

    if form.is_valid():
      form.instance.created_by = request.user
      quiz = form.save()

      questions = request.FILES.get('questions', False)
      if questions:
        question_num = 1
        for line in questions:
          row = line.split(',')
          if len(row) == 2:
            quiz.add_subjective_question(question=row[0], score=row[1], question_num=question_num)
          elif len(row) > 2:
            quiz.add_mc_question(question=row[0], score=row[1], answer=row[2], choices=row[3:], question_num=question_num)

          question_num += 1

      return self.form_valid(form)
    else:
      return self.form_invalid(form)

quiz/templates/quiz/admin-home.html
{% extends 'base.html' %}
{% load quiz_extras %}

{% block title %}Home{% endblock %}


{% block content %}
  <div class="list-group">

    <div class="list-group-item active">
      <h4 class="list-group-item-heading">Actions</h4>
    </div>

    <a href="{% url 'quiz:register-school' %}" class="list-group-item">
      <h4 class="list-group-item-heading">Register School</h4>
    </a>

    <a href="{% url 'quiz:register-teacher' %}" class="list-group-item">
      <h4 class="list-group-item-heading">Register Teacher</h4>
    </a>

    <a href="{% url 'quiz:new-quiz' %}" class="list-group-item">
      <h4 class="list-group-item-heading">Add Quiz</h4>
    </a>
  </div>
{% endblock %}

quiz/templates/quiz/home.html
{% extends 'base.html' %}
{% load quiz_extras %}

{% block title %}Home{% endblock %}


{% block content %}
  <div class="row">

    <div class="col-md-8 col-md-offset-2">

      {% if request.user.student.get_active_quizzes.count > 0 %}

        <div class="list-group">

          <div class="list-group-item active">
            <h4 class="list-group-item-heading">Active Quizzes</h4>
          </div>

          {% for quiz in request.user.student.get_active_quizzes %}
            <a href="{% url 'quiz:quiz-question' quiz_id=quiz.id question_num=1 %}" class="list-group-item">
              <h4 class="list-group-item-heading">{{ quiz.name }}</h4>
              <p class="list-group-item-text">{{ quiz.quiz_commence_date | date:'d/m/Y g:i A' }}</p>
            </a>
          {% endfor %}

        </div>

      {% endif %}

    </div>

  </div>


  <div class="row">

    <div class="col-md-8 col-md-offset-2">

      {% if request.user.student.get_attempted_quizzes.count > 0 %}

        <div class="list-group">

          <div class="list-group-item active">
            <h4 class="list-group-item-heading">Attempted Quizzes</h4>
          </div>

          {% for quiz in request.user.student.get_attempted_quizzes %}
            <a href="{% url 'quiz:quiz-result' quiz_id=quiz.id student_id=request.user.student.id %}" class="list-group-item">
              <h4 class="list-group-item-heading">{{ quiz.name }}</h4>
              <p class="list-group-item-text">
                Date : {{ quiz.quiz_commence_date | date:'d/m/Y g:i A' }}
                <br>
                Score : {{ request.user.student|get_score:quiz }}/{{ quiz.get_total_score }}
                <br>
                <small>Click to review answers</small>
              </p>
            </a>
          {% endfor %}

        </div>

      {% endif %}

    </div>

  </div>


  <div class="row">

    <div class="col-md-8 col-md-offset-2">

      {% if request.user.student.get_upcoming_quizzes.count > 0 %}

        <div class="list-group">

          <div class="list-group-item active">
            <h4 class="list-group-item-heading">Upcoming Quizzes</h4>
          </div>

          {% for quiz in request.user.student.get_upcoming_quizzes %}
            <div class="list-group-item">
              <h4 class="list-group-item-heading">{{ quiz.name }}</h4>
              <p class="list-group-item-text">{{ quiz.quiz_commence_date | date:'d/m/Y g:i A' }}</p>
            </div>
          {% endfor %}

        </div>

      {% endif %}

    </div>

  </div>
{% endblock %}

quiz/templates/quiz/new-quiz.html
{% extends 'base.html' %}

{% block title %}New Quiz{% endblock %}

{% block content %}
  <form enctype='multipart/form-data' action="{% url 'quiz:new-quiz' %}" method="post">
    {% include 'form_template.html' %}
  </form>
{% endblock %}

quiz/templates/quiz/quiz-question.html
{% extends 'base.html' %}
{% load quiz_extras %}

{% block title %}Quiz - {{ quiz.name }}{% endblock %}


{% block content %}
  <div class="jumbotron">
    <h1>Question No. {{ question.question_num }}</h1>
    <p>{{ question.text }}</p>
  </div>

  <form action="{% url 'quiz:quiz-question' quiz_id=question.quiz.id question_num=question.question_num%}" method="post">
   {% csrf_token %}
    {% if is_mcq %}
      {% for choice in question.choices.all %}
        <div class="row">
          <div class="col-sm-1 col-sm-offset-2">
            <input name="answer" type="radio" value="{{ choice.id }}" id="answer{{ choice.id }}">
          </div>
          <div class="col-sm-8 col-sm-offset-1">
            <label for="answer{{ choice.id }}">{{ choice.text }}</label>
          </div>
        </div>
      {% endfor %}
    {% else %}
      <div class="row">
        <textarea class="form-control" name="answer" placeholder="Type your answer here" rows="10"></textarea>
      </div>
    {% endif %}
    <div class="row text-right" style="margin-top: 50px;">
      <button type="submit" class="btn btn-default">Next</button>
    </div>
  </form>
{% endblock %}

quiz/templates/quiz/quiz_result.html
{% extends 'base.html' %}
{% load quiz_extras %}

{% block title %}Quiz - {{ quiz.name }}{% endblock %}


{% block content %}
  <div class="jumbotron">
    <h1 class="text-center">Quiz: {{ quiz.name }}</h1>
    <p class="text-center">Score: {{ score }}/{{ quiz.get_total_score }}</p>
    <p class="text-center">Date: {{ quiz.quiz_commence_date | date:'d/m/Y g:i A' }}</p>
  </div>

  <div class="row">
    {% for answer in answer_sheet%}
      <div class="list-group">

        <div class="list-group-item active">
          <h4 class="list-group-item-heading">Question {{ answer.question.question_num }}: {{ answer.question.text }}</h4>
        </div>


        <div class="list-group-item" {% if answer.score == 0 %}style="background-color: pink" {% endif %}>
          <h4 class="list-group-item-heading">Submitted Answer: {{ answer.answer }}</h4>

          {% if answer.content_type.model == 'mcquestion' %}
            <p class="list-group-item-text">Score: {{ answer.score }}/{{ answer.question.score }}</p>
            {% if answer.score == 0 %}
              <p class="list-group-item-text"><strong>Correct answer: {{ answer.question.answer.text }}</strong></p>
            {% endif %}
          {% else %}
            {% if answer.score == None %}
              <p class="list-group-item-text">Answer not yet scored.</p>
            {% endif %}

            <p class="list-group-item-text">Score: <span id="score_text_{{ answer.id }}">{% if answer.score == None %}?{% else %}{{ answer.score }}{% endif %}</span>/{{ answer.question.score }}</p>

            {% if request.user.teacher %}
              <div class="list-group-item-text row">
                <div class="col-sm-4 col-sm-oddfet-3"><input type="number" id="score{{ answer.id }}" placeholder="Score"></div>
                <div class="col-sm-2" ><button class="btn btn-default" onclick="submit_score({{ answer.id }})">Submit</button></div>
              </div>
            {% endif %}
          {% endif %}
        </div>

      </div>

    {% endfor %}
  </div>
{% endblock %}

{% block script_postjquery %}
  <script>
    function submit_score(answer_id) {
      var score = $('#score' + answer_id).val();
      $.ajax({
          url: "{% url 'quiz:submit-score' %}",
          method: 'POST',

          data: {
            answer_id: answer_id,
            score: score,
          },
          success: function(data) {
            $('#score_text_' + answer_id).text(score);
            $('#score' + answer_id).val('');
          }
        }
      );
    }
  </script>
{% endblock %}

quiz/templates/quiz/register-school.html
{% extends 'base.html' %}

{% block title %}Home{% endblock %}

{% block content %}
  <form method="post" action="{% url 'quiz:register-school' %}">
    {% include 'form_template.html' %}
  </form>
{% endblock %}

quiz/templates/quiz/teacher-home.html
{% extends 'base.html' %}
{% load quiz_extras %}

{% block title %}Home{% endblock %}


{% block content %}
  <div class="row">

    <div class="list-group">

          <div class="list-group-item active">
            <h4 class="list-group-item-heading">Students</h4>
          </div>

          {% for student in request.user.teacher.get_students %}
            <a href="{% url 'quiz:teacher-student' pk=student.id %}" class="list-group-item">
              {{ student.first_name }} {{ student.middle_name }} {{ student.last_name }}
            </a>
          {% endfor %}
    </div>

  </div>

  <div class="row">

    <div class="list-group">

          <div class="list-group-item active">
            <h4 class="list-group-item-heading">Quiz</h4>
          </div>

          {% for quiz in request.user.teacher.get_past_quizzes %}
            <a href="{% url 'quiz:teacher-quiz' quiz_id=quiz.id %}" class="list-group-item">
            <h4 class="list-group-item-heading">{{ quiz.name }}</h4>
            <p class="list-group-item-text">
              Date : {{ quiz.quiz_commence_date | date:'d/m/Y g:i A' }}
            </p>
          </a>
          {% endfor %}
    </div>

  </div>
{% endblock %}

quiz/templates/quiz/teacher-quiz.html
{% extends 'base.html' %}
{% load quiz_extras %}

{% block title %}Home{% endblock %}


{% block content %}
  <div class="row">

    <div class="list-group">

      <div class="list-group-item active">
        <h4 class="list-group-item-heading">Students</h4>
      </div>

      {% for student in students %}
        <a href="{% url 'quiz:quiz-result' quiz_id=quiz.id student_id=student.id %}" class="list-group-item">
          <h4>{{ student.first_name }} {{ student.middle_name }} {{ student.last_name }}</h4>

          <p class="list-group-item-text">
            Date : {{ quiz.quiz_commence_date | date:'d/m/Y g:i A' }}
            <br>
            Score : {{ student|get_score:quiz }}/{{ quiz.get_total_score }}
            <br>
            <small>Click to review and score answers</small>
          </p>
        </a>
      {% endfor %}
    </div>

  </div>
{% endblock %}

quiz/templates/quiz/teacher-student.html
{% extends 'base.html' %}
{% load quiz_extras %}

{% block title %}Home{% endblock %}


{% block content %}

  <div class="row">

    <div class="col-md-8 col-md-offset-2">

      <div class="list-group">

        <div class="list-group-item active">
          <h4 class="list-group-item-heading">{{ student.first_name }} {{ student.middle_name }}  {{ student.last_name }} : Attempted Quizzes</h4>
        </div>

        {% for quiz in student.get_attempted_quizzes %}
          <a href="{% url 'quiz:quiz-result' quiz_id=quiz.id student_id=student.id %}" class="list-group-item">
            <h4 class="list-group-item-heading">{{ quiz.name }}</h4>
            <p class="list-group-item-text">
              Date : {{ quiz.quiz_commence_date | date:'d/m/Y g:i A' }}
              <br>
              Score : {{ student|get_score:quiz }}/{{ quiz.get_total_score }}
              <br>
              <small>Click to review and score answers</small>
            </p>
          </a>
        {% endfor %}

      </div>

    </div>

  </div>

{% endblock %}