SchoolQuiz/urls.py
from django.conf.urls import url, include
from django.contrib import admin

from SchoolQuiz import settings

urlpatterns = [
  url(r'^admin/', admin.site.urls),
  url(r'^auth/', include('auth0.urls', namespace='auth0')),
  url(r'^', include('quiz.urls', namespace='quiz')),
]

auth0/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^logout/$', views.LogoutView.as_view(), name='logout'),
    url(r'^login/$', views.LoginView.as_view(), name='login'),
    url(r'^signup/$', views.RegisterView.as_view(), name='register'),

]

quiz/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
  url(r'^$', views.HomeView.as_view(), name='home'),
  url(r'^register-school/$', views.RegisterSchool.as_view(), name='register-school'),
  url(r'^quiz/new/$', views.NewQuiz.as_view(), name='new-quiz'),

  url(r'^quiz/(?P<quiz_id>[0-9]+)/(?P<question_num>[0-9]+)/$', views.QuizQuestionView.as_view(), name='quiz-question'),
  url(r'^quiz/result/(?P<student_id>[0-9]+)/(?P<quiz_id>[0-9]+)/$', views.QuizResultView.as_view(), name='quiz-result'),

  url(r'^register-teacher/$', views.RegisterTeacher.as_view(), name='register-teacher'),
  url(r'^teacher/$', views.TeacherHomeView.as_view(), name='teacher-home'),
  url(r'^^teacher/student/(?P<pk>[0-9]+)/$', views.TeacherStudentView.as_view(), name='teacher-student'),
  url(r'teacher/quiz/(?P<quiz_id>[0-9]+)/$', views.TeacherQuizView.as_view(), name='teacher-quiz'),
  url(r'^teacher/submit-score/$', views.SubmitScoreView.as_view(), name='submit-score'),

  url(r'^adm/home', views.AdminHomeView.as_view(), name='admin-home'),
]

templates/base.html
{% load staticfiles %}
{% load quiz_extras %}

<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>{% block title %}Social Network{% endblock %}</title>

  <meta name="viewport" content="width=device-width, initial-scale=1">

  <!-- Latest compiled and minified CSS -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">

  <!-- Optional theme -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap-theme.min.css" integrity="sha384-fLW2N01lMqjakBkx3l/M9EahuwpSfeNvV63J5ezn3uZzapT0u7EYsXMjQV+0En5r" crossorigin="anonymous">

  <link rel="stylesheet" type="text/css" href="{% static 'css/theme.css' %}">

  {% block head %}
  {% endblock head %}
</head>
<body role="document">

<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="{% url 'quiz:home' %}">School Quiz</a>
    </div>
    <div id="navbar" class="navbar-collapse collapse pull-right">
      <ul class="nav navbar-nav ">
        <li class="active"><a href="{% url 'quiz:home' %}"><span class="glyphicon glyphicon-home"></span></a></li>

        {% if user.is_anonymous %}
          <li><a href="{% url 'auth0:login' %}">Sign In</a></li>
          <li><a href="{% url 'auth0:register' %}">Sign Up</a></li>
        {% else %}
          {% with greeting='Hi Hola Hello Hey Hie'%}
            <li><a href="#">{{ greeting.split|random }}, {{ user.first_name }}</a></li>
          {% endwith %}
          <li><a href="{% url 'auth0:logout' %}">Sign out</a></li>
        {% endif %}

      </ul>
    </div><!--/.nav-collapse -->
  </div>
</nav>

<div class="{% block container_class %}container{% endblock %}" role="main">

  {% block content %}
  {% endblock %}
</div>


{% block script_prejquery %}
{% endblock %}

<!-- Latest Jquery -->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
<!-- Latest compiled and minified JavaScript -->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js" integrity="sha384-0mSbJDEHialfmuBBQP6A4Qrprq5OVfW37PRR3j5ELqxss1yVqOtnepnHVP9aJ7xS" crossorigin="anonymous"></script>

<script>
  $(document).ready(function () {
    $('input').addClass('form-control')
  })
</script>

<script type="application/javascript" src="{% static 'js/ajax_workaround.js' %}" ></script>
{% block script_postjquery %}
{% endblock %}
</body>
</html>

templates/form_template.html
{% csrf_token %}
{% if form.errors %}{{ form.errors }}{% endif %} {% for field in form.visible_fields %}
  <div class="col-md-6 col-md-offset-3 form-group">
    <div class="col-md-4">{{ field.label_tag }}</div>
    <div class="col-md-8">{{ field }}</div>
  </div>
{% endfor %} {% for hidden in form.hidden_fields %} {{ hidden }} {% endfor %}
<div class="form-group">
  <div class="col-sm-offset-2 col-sm-10 text-center">
    <button type="submit" class="btn btn-primary">Submit</button>
  </div>
</div>